services:
  node:
    build: ./frontend
    container_name: vue
    ports:
      - "3000:3000"
    networks:
      - frontend

  php:
    build: ./backend
    container_name: php
    ports:
      - "8000:8000"
    networks:
      - frontend

networks:
  frontend:
