services:
  php:
    build: .
    container_name: php
    volumes:
      - ./:/var/www/html

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main
    ports:
      # To allow the host machine to access the ports below, modify the lines below.
      # For example, to allow the host to connect to port 3306 on the container, you would change
      # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
      # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
        
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      - MAILPIT_RELAY=127.0.0.1:25

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb # Nom du conteneur MariaDB
      PMA_PORT: 3306    # Port interne utilisé par phpMyAdmin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80" # Accès à phpMyAdmin via le port 8081

volumes:
  db_data: