nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Host', 'User-Agent', 'Accept', 'Accept-Encoding', 'Connection']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*'] # Si vous voulez autoriser tous les en-têtes
            allow_methods: ['POST', 'OPTIONS', 'PUT', 'GET', 'DELETE']
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+']
            allow_headers: ['Content-Type', 'Authorization', 'Host', 'User-Agent', 'Accept', 'Accept-Encoding', 'Connection']
            allow_methods: ['POST', 'OPTIONS', 'PUT', 'GET', 'DELETE']
            max_age: 3600
            hosts: ['^api\.']
