nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:8080'] # Autoriser les requêtes depuis votre frontend
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE'] # OPTIONS inclus explicitement
            max_age: 3600
        '^/sales':
            allow_origin: ['http://localhost:8080']
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'OPTIONS']
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: ['^http://localhost:[0-9]+']
            allow_headers: ['*']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE'] # OPTIONS inclus explicitement
            max_age: 3600
            hosts: ['^api\.']
